export const PLANS = {
  starter: {
    name: "Starter",
    description: "For small churches just getting started",
    monthlyPrice: 0,
    yearlyPrice: 0,
    memberLimit: 75,
    adminLimit: 1,
    features: [
      "Up to 75 members",
      "1 admin user",
      "People & household management",
      "Basic attendance tracking",
      "Event scheduling",
      "Liturgy builder (2 services / month)",
      "CSV import",
      "Community support",
    ],
  },
  growth: {
    name: "Growth",
    description: "For growing churches that need deeper insights",
    monthlyPrice: 49,
    yearlyPrice: 468,
    memberLimit: 500,
    adminLimit: 5,
    features: [
      "Up to 500 members",
      "5 admin users",
      "Everything in Starter, plus:",
      "Unlimited liturgy builder — all 10 traditions",
      "Print-ready bulletins & planning checklists",
      "Warmth analytics & scoring",
      "AI-powered insights",
      "Group health monitoring",
      "Cooling alerts & follow-ups",
      "Platform import connectors",
      "Email support",
    ],
    popular: true,
  },
  pro: {
    name: "Pro",
    description: "For large churches with advanced needs",
    monthlyPrice: 149,
    yearlyPrice: 1428,
    memberLimit: -1,
    adminLimit: -1,
    features: [
      "Unlimited members",
      "Unlimited admin users",
      "Everything in Growth, plus:",
      "Multi-campus support",
      "Advanced AI assistant",
      "Custom warmth models",
      "API access & webhooks",
      "Priority phone & email support",
      "Dedicated onboarding",
    ],
  },
} as const;

export type PlanKey = keyof typeof PLANS;
